auto:        true

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:year/:month/:day

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
